#!/usr/bin/env python
import os
os.environ['TRANSFORMERS_CACHE'] = os.path.abspath(
    os.path.join(os.path.dirname(__file__), 'tmp', 'mulabel')
)

from emma.core import ExecModule


if __name__ == "__main__":
    module: ExecModule = ExecModule.get(__file__)
    module.execute()
    